package main

import (
	"os"
)

const MOONSTREAM_DROPPER_POLYGON_CONTRACT_ADDRESS = "0x7bbf900Ded826D5A16a27dF028018673E521B35d"

var (
	MOONSTREAM_DROPPER_CLAIMANTS_INPUT         = os.Getenv("MOONSTREAM_DROPPER_CLAIMANTS_INPUT")
	MOONSTREAM_DROPPER_CUSTOM_CONTRACT_ADDRESS = os.Getenv("MOONSTREAM_DROPPER_CUSTOM_CONTRACT_ADDRESS")
	MOONSTREAM_DROPPER_CLAIM_ID                = os.Getenv("MOONSTREAM_DROPPER_CLAIM_ID")

	KEYFILE_PATH     = os.Getenv("KEYFILE_PATH")
	PRIVATE_KEY      = os.Getenv("PRIVATE_KEY")
	KEYFILE_PASSWORD = os.Getenv("KEYFILE_PASSWORD")

	JSON_RPC_URI = os.Getenv("JSON_RPC_URI")

	MOONSTREAM_DROPPER_CLAIMANTS_OUTPUT = os.Getenv("MOONSTREAM_DROPPER_CLAIMANTS_OUTPUT")
)
