export const UNIM_ADDRESS =
  process.env.NEXT_PUBLIC_UNIMLK_ADDRESS ??
  "not defined NEXT_PUBLIC_UNIMLK_ADDRESS";
export const BOTTLER_ADDRESS =
  process.env.NEXT_PUBLIC_BOTTLER_ADDRESS ??
  "Not defined NEXT_PUBLIC_BOTTLER_ADDRESS";

export const TERMINUS_DIAMOND_ADDRESS =
  process.env.NEXT_PUBLIC_TERMINUS_ADDRESS ??
  "Not defined NEXT_PUBLIC_TERMINUS_ADDRESS";
